"""empty message

Revision ID: 9fc3afadc474
Revises: 972a4f09b456
Create Date: 2020-07-29 07:12:28.787740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fc3afadc474'
down_revision = '972a4f09b456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessments', 'id',
               existing_type=postgresql.UUID(),
               comment='ID оценки',
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('assessments', 'photo_id',
               existing_type=postgresql.UUID(),
               comment='ID фотографии.',
               existing_nullable=True)
    op.alter_column('assessments', 'rating',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment='Рейтинг фотографии.',
               existing_nullable=True)
    op.alter_column('assessments', 'user_id',
               existing_type=postgresql.UUID(),
               comment='ID пользователя.',
               existing_nullable=True)
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.alter_column('photos', 'id',
               existing_type=postgresql.UUID(),
               comment='Id photo.',
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=postgresql.UUID(),
               comment='ID пользователя',
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(),
               comment='Логин пользователя',
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=postgresql.BYTEA(),
               comment='Пароль пользователя',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='Пароль пользователя',
               existing_nullable=False)
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Логин пользователя',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='ID пользователя',
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.alter_column('photos', 'id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='Id photo.',
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.alter_column('assessments', 'user_id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='ID пользователя.',
               existing_nullable=True)
    op.alter_column('assessments', 'rating',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Рейтинг фотографии.',
               existing_nullable=True)
    op.alter_column('assessments', 'photo_id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='ID фотографии.',
               existing_nullable=True)
    op.alter_column('assessments', 'id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='ID оценки',
               existing_server_default=sa.text('uuid_generate_v4()'))
    # ### end Alembic commands ###
